version: "3.9"
services:
  be_ayds:
    build: ./BE
    ports:
      - "4000:4000"
    links:
      - POSTGRES
  POSTGRES:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ayds
      - POSTGRES_PASSWORD=1234567890
  fe_ayds:
    build: ./fe_ayds
    ports:
      - "8000:80"
    